import { StyleSheet } from 'react-native'

import { colors, spacing, typography } from '@/theme'

export const styles = StyleSheet.create({
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    justifyContent: 'flex-end',
    zIndex: 1000,
    elevation: 24,
    overflow: 'visible',
  },
  backdrop: { ...StyleSheet.absoluteFill, backgroundColor: colors.overlay },
  sheet: {
    maxHeight: '88%',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    backgroundColor: colors.white,
  },
  sheetInner: {
    gap: spacing.lg,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sheetHeaderCopy: { flex: 1, minWidth: 0, marginRight: spacing.sm },
  sheetTitle: {
    ...typography.title,
    fontSize: 22,
    lineHeight: 28,
    color: colors.neutral950,
  },
  sheetDescription: { ...typography.body, color: colors.neutral600 },
  sheetContent: { paddingBottom: spacing.sm },
  iconButton: {
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trigger: {
    minHeight: 44,
    maxWidth: 180,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: 8,
    borderColor: colors.neutral300,
    borderWidth: 1,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.sm,
  },
  triggerPressed: { opacity: 0.72 },
  triggerText: {
    ...typography.tabLabel,
    flexShrink: 1,
    color: colors.neutral950,
  },
  teamList: { gap: spacing.sm },
  teamRow: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 10,
    borderColor: colors.neutral300,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
  },
  selectedTeamRow: {
    borderColor: colors.neutral950,
    backgroundColor: colors.neutral950,
  },
  teamRowPressed: { opacity: 0.72 },
  teamCopy: { gap: 2 },
  teamName: { ...typography.label, color: colors.neutral950 },
  teamCode: { ...typography.tabLabel, color: colors.neutral500 },
  selectedTeamText: { color: colors.white },
  stateBlock: { gap: spacing.sm },
  stateText: { ...typography.body, color: colors.neutral600 },
  errorText: { ...typography.body, color: colors.error },
  secondaryButton: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    borderColor: colors.neutral300,
    borderWidth: 1,
    paddingHorizontal: spacing.lg,
  },
  secondaryButtonText: { ...typography.label, color: colors.neutral950 },
})
